package xlsys.base.test.model;

import xlsys.base.model.ITableModel;
import java.math.BigDecimal;

/**
 * This class is automatically generated by the program of Lewis.
 * @author Lewis
 *
 */
public class TestModel implements ITableModel
{
	private static final long serialVersionUID = -2967901964786827555L;
	
	private BigDecimal idx;
	private String name;
	private BigDecimal value;

	protected TestModel() {}

	public TestModel(BigDecimal idx)
	{
		this.idx = idx;
	}

	public BigDecimal getIdx()
	{
		return idx;
	}

	protected void setIdx(BigDecimal idx)
	{
		this.idx = idx;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public BigDecimal getValue()
	{
		return value;
	}

	public void setValue(BigDecimal value)
	{
		this.value = value;
	}

	@Override
	public String getRefTableName()
	{
		return "xlsys_test";
	}
}