package xlsys.base.model;

import java.math.BigDecimal;
import java.util.List;
import java.util.ArrayList;

/**
 * This class is automatically generated by the program of Lewis.
 * @author Lewis
 *
 */
public class FrameModel implements ITableModel
{
	private static final long serialVersionUID = 8231607259239982237L;
	
	private BigDecimal frameid;
	private String name;
	private BigDecimal platform;
	private String innerlisteners;
	private byte[] scriptlistener;
	private List<FrameParamModel> frameParamList;
	private List<FrameDetailModel> frameDetailList;

	protected FrameModel() {}

	public FrameModel(BigDecimal frameid)
	{
		this.frameid = frameid;
	}

	public BigDecimal getFrameid()
	{
		return frameid;
	}

	protected void setFrameid(BigDecimal frameid)
	{
		this.frameid = frameid;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public BigDecimal getPlatform()
	{
		return platform;
	}

	public void setPlatform(BigDecimal platform)
	{
		this.platform = platform;
	}

	public String getInnerlisteners()
	{
		return innerlisteners;
	}

	public void setInnerlisteners(String innerlisteners)
	{
		this.innerlisteners = innerlisteners;
	}

	public byte[] getScriptlistener()
	{
		return scriptlistener;
	}

	public void setScriptlistener(byte[] scriptlistener)
	{
		this.scriptlistener = scriptlistener;
	}

	public List<FrameParamModel> getFrameParamList()
	{
		return frameParamList;
	}

	public void setFrameParamList(List<FrameParamModel> frameParamList)
	{
		this.frameParamList = frameParamList;
	}

	public void addFrameParam(FrameParamModel frameParam)
	{
		if(frameParamList==null) frameParamList = new ArrayList<FrameParamModel>();
		frameParamList.add(frameParam);
	}

	public List<FrameDetailModel> getFrameDetailList()
	{
		return frameDetailList;
	}

	public void setFrameDetailList(List<FrameDetailModel> frameDetailList)
	{
		this.frameDetailList = frameDetailList;
	}

	public void addFrameDetail(FrameDetailModel frameDetail)
	{
		if(frameDetailList==null) frameDetailList = new ArrayList<FrameDetailModel>();
		frameDetailList.add(frameDetail);
	}
	
	public FrameDetailModel getFrameDetailModel(String fdtid)
	{
		FrameDetailModel fdm = null;
		if(frameDetailList!=null)
		{
			for(FrameDetailModel fdmTemp : frameDetailList)
			{
				if(fdmTemp.getFdtid().equals(fdtid))
				{
					fdm = fdmTemp;
					break;
				}
			}
		}
		return fdm;
	}

	@Override
	public String getRefTableName()
	{
		return "xlv2_frame";
	}
}