package xlsys.base.model;

import java.math.BigDecimal;

/**
 * This class is automatically generated by the program of Lewis.
 * @author Lewis
 *
 */
public class FrameParamModel implements ITableModel
{
	private static final long serialVersionUID = 8412854848898198373L;
	
	private BigDecimal frameid;
	private String attrname;
	private String attrvalue;

	protected FrameParamModel() {}

	public FrameParamModel(BigDecimal frameid, String attrname)
	{
		this.frameid = frameid;
		this.attrname = attrname;
	}

	public BigDecimal getFrameid()
	{
		return frameid;
	}

	protected void setFrameid(BigDecimal frameid)
	{
		this.frameid = frameid;
	}

	public String getAttrname()
	{
		return attrname;
	}

	protected void setAttrname(String attrname)
	{
		this.attrname = attrname;
	}

	public String getAttrvalue()
	{
		return attrvalue;
	}

	public void setAttrvalue(String attrvalue)
	{
		this.attrvalue = attrvalue;
	}

	@Override
	public String getRefTableName()
	{
		return "xlv2_frameparam";
	}
}