package xlsys.base.model;

import java.math.BigDecimal;
import java.util.List;

import java.util.ArrayList;

/**
 * This class is automatically generated by the program of Lewis.
 * @author Lewis
 *
 */
public class FrameModel implements ITableModel
{
	private static final long serialVersionUID = 2095155010569151599L;
	
	private BigDecimal frameid;
	private String name;
	private List<FrameDetailModel> frameDetailList;

	protected FrameModel() {}

	public FrameModel(BigDecimal frameid)
	{
		this.frameid = frameid;
	}

	public BigDecimal getFrameid()
	{
		return frameid;
	}

	protected void setFrameid(BigDecimal frameid)
	{
		this.frameid = frameid;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public List<FrameDetailModel> getFrameDetailList()
	{
		return frameDetailList;
	}

	public void setFrameDetailList(List<FrameDetailModel> frameDetailList)
	{
		this.frameDetailList = frameDetailList;
	}

	public void addFrameDetail(FrameDetailModel frameDetail)
	{
		if(frameDetailList==null) frameDetailList = new ArrayList<FrameDetailModel>();
		frameDetailList.add(frameDetail);
	}
	
	public FrameDetailModel getFrameDetailModel(String fdtid)
	{
		FrameDetailModel fdm = null;
		if(frameDetailList!=null)
		{
			for(FrameDetailModel fdmTemp : frameDetailList)
			{
				if(fdmTemp.getFdtid().equals(fdtid))
				{
					fdm = fdmTemp;
					break;
				}
			}
		}
		return fdm;
	}

	@Override
	public String getRefTableName()
	{
		return "xlv2_frame";
	}
}