package xlsys.base.model;

import java.math.BigDecimal;
import java.util.List;
import java.util.ArrayList;

/**
 * This class is automatically generated by the program of Lewis.
 * @author Lewis
 *
 */
public class FrameDetailModel implements ITableModel
{
	private static final long serialVersionUID = 2985631319675183292L;
	
	private BigDecimal frameid;
	private String fdtid;
	private String name;
	private BigDecimal uimid;
	private String diyimpl;
	private String registname;
	private BigDecimal viewid;
	private List<FrameDetailParamModel> frameDetailParamList;

	protected FrameDetailModel() {}

	public FrameDetailModel(BigDecimal frameid, String fdtid)
	{
		this.frameid = frameid;
		this.fdtid = fdtid;
	}

	public BigDecimal getFrameid()
	{
		return frameid;
	}

	protected void setFrameid(BigDecimal frameid)
	{
		this.frameid = frameid;
	}

	public String getFdtid()
	{
		return fdtid;
	}

	protected void setFdtid(String fdtid)
	{
		this.fdtid = fdtid;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public BigDecimal getUimid()
	{
		return uimid;
	}

	public void setUimid(BigDecimal uimid)
	{
		this.uimid = uimid;
	}

	public String getDiyimpl()
	{
		return diyimpl;
	}

	public void setDiyimpl(String diyimpl)
	{
		this.diyimpl = diyimpl;
	}

	public String getRegistname()
	{
		return registname;
	}

	public void setRegistname(String registname)
	{
		this.registname = registname;
	}

	public BigDecimal getViewid()
	{
		return viewid;
	}

	public void setViewid(BigDecimal viewid)
	{
		this.viewid = viewid;
	}

	public List<FrameDetailParamModel> getFrameDetailParamList()
	{
		return frameDetailParamList;
	}

	public void setFrameDetailParamList(List<FrameDetailParamModel> frameDetailParamList)
	{
		this.frameDetailParamList = frameDetailParamList;
	}

	public void addFrameDetailParam(FrameDetailParamModel frameDetailParam)
	{
		if(frameDetailParamList==null) frameDetailParamList = new ArrayList<FrameDetailParamModel>();
		frameDetailParamList.add(frameDetailParam);
	}

	@Override
	public String getRefTableName()
	{
		return "xlv2_framedetail";
	}
}