package xlsys.base.model;


/**
 * This class is automatically generated by the program of Lewis.
 * @author Lewis
 *
 */
public class MenuHandlerParamModel implements ITableModel
{
	private String menuid;
	private String attrname;
	private String attrvalue;

	protected MenuHandlerParamModel() {}

	public MenuHandlerParamModel(String menuid, String attrname)
	{
		this.menuid = menuid;
		this.attrname = attrname;
	}

	public String getMenuid()
	{
		return menuid;
	}

	protected void setMenuid(String menuid)
	{
		this.menuid = menuid;
	}

	public String getAttrname()
	{
		return attrname;
	}

	protected void setAttrname(String attrname)
	{
		this.attrname = attrname;
	}

	public String getAttrvalue()
	{
		return attrvalue;
	}

	public void setAttrvalue(String attrvalue)
	{
		this.attrvalue = attrvalue;
	}

	@Override
	public String getRefTableName()
	{
		return "xlv2_menuhandlerparam";
	}
}