package xlsys.base.model;

import java.math.BigDecimal;
import xlsys.base.io.attachment.XlsysAttachment;
import java.util.List;
import java.util.ArrayList;

/**
 * This class is automatically generated by the program of Lewis.
 * @author Lewis
 *
 */
public class ToolModel implements ITableModel
{
	private static final long serialVersionUID = 6196182691886113828L;
	
	private String toolid;
	private String levelid;
	private BigDecimal handlerid;
	private String name;
	private BigDecimal type;
	private XlsysAttachment icon;
	private String shortcut;
	private List<ToolRightModel> toolRightList;
	private List<ToolHandlerParamModel> toolHandlerParamList;

	protected ToolModel() {}

	public ToolModel(String toolid)
	{
		this.toolid = toolid;
	}

	public String getToolid()
	{
		return toolid;
	}

	protected void setToolid(String toolid)
	{
		this.toolid = toolid;
	}

	public String getLevelid()
	{
		return levelid;
	}

	public void setLevelid(String levelid)
	{
		this.levelid = levelid;
	}

	public BigDecimal getHandlerid()
	{
		return handlerid;
	}

	public void setHandlerid(BigDecimal handlerid)
	{
		this.handlerid = handlerid;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public BigDecimal getType()
	{
		return type;
	}

	public void setType(BigDecimal type)
	{
		this.type = type;
	}

	public XlsysAttachment getIcon()
	{
		return icon;
	}

	public void setIcon(XlsysAttachment icon)
	{
		this.icon = icon;
	}

	public String getShortcut()
	{
		return shortcut;
	}

	public void setShortcut(String shortcut)
	{
		this.shortcut = shortcut;
	}

	public List<ToolRightModel> getToolRightList()
	{
		return toolRightList;
	}

	public void setToolRightList(List<ToolRightModel> toolRightList)
	{
		this.toolRightList = toolRightList;
	}

	public void addToolRight(ToolRightModel toolRight)
	{
		if(toolRightList==null) toolRightList = new ArrayList<ToolRightModel>();
		toolRightList.add(toolRight);
	}

	public List<ToolHandlerParamModel> getToolHandlerParamList()
	{
		return toolHandlerParamList;
	}

	public void setToolHandlerParamList(List<ToolHandlerParamModel> toolHandlerParamList)
	{
		this.toolHandlerParamList = toolHandlerParamList;
	}

	public void addToolHandlerParam(ToolHandlerParamModel toolHandlerParam)
	{
		if(toolHandlerParamList==null) toolHandlerParamList = new ArrayList<ToolHandlerParamModel>();
		toolHandlerParamList.add(toolHandlerParam);
	}

	@Override
	public String getRefTableName()
	{
		return "xlv2_tool";
	}
}