package xlsys.base.model;

import java.math.BigDecimal;

/**
 * This class is automatically generated by the program of Lewis.
 * @author Lewis
 *
 */
public class ToolRightModel implements ITableModel
{
	private static final long serialVersionUID = -6487966862710087539L;
	
	private String toolid;
	private BigDecimal idx;
	private BigDecimal righttype;
	private String rightvalue;

	protected ToolRightModel() {}

	public ToolRightModel(String toolid, BigDecimal idx)
	{
		this.toolid = toolid;
		this.idx = idx;
	}

	public String getToolid()
	{
		return toolid;
	}

	protected void setToolid(String toolid)
	{
		this.toolid = toolid;
	}

	public BigDecimal getIdx()
	{
		return idx;
	}

	protected void setIdx(BigDecimal idx)
	{
		this.idx = idx;
	}

	public BigDecimal getRighttype()
	{
		return righttype;
	}

	public void setRighttype(BigDecimal righttype)
	{
		this.righttype = righttype;
	}

	public String getRightvalue()
	{
		return rightvalue;
	}

	public void setRightvalue(String rightvalue)
	{
		this.rightvalue = rightvalue;
	}

	@Override
	public String getRefTableName()
	{
		return "xlv2_toolright";
	}
}