package xlsys.base.model;

import java.math.BigDecimal;

/**
 * This class is automatically generated by the program of Lewis.
 * @author Lewis
 *
 */
public class UIModuleModel implements ITableModel
{
	private static final long serialVersionUID = -6650534107983129643L;
	
	private BigDecimal uimid;
	private String name;
	private String defaultimpl;

	protected UIModuleModel() {}

	public UIModuleModel(BigDecimal uimid)
	{
		this.uimid = uimid;
	}

	public BigDecimal getUimid()
	{
		return uimid;
	}

	protected void setUimid(BigDecimal uimid)
	{
		this.uimid = uimid;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getDefaultimpl()
	{
		return defaultimpl;
	}

	public void setDefaultimpl(String defaultimpl)
	{
		this.defaultimpl = defaultimpl;
	}

	@Override
	public String getRefTableName()
	{
		return "xlv2_uimodule";
	}
}