package xlsys.base.model;

import java.math.BigDecimal;
import java.util.List;
import java.util.ArrayList;

/**
 * This class is automatically generated by the program of Lewis.
 * @author Lewis
 *
 */
public class ViewColumnModel implements ITableModel
{
	private static final long serialVersionUID = -6819795107594182790L;
	
	private BigDecimal viewid;
	private BigDecimal idx;
	private String name;
	private String colname;
	private String sqlexp;
	private BigDecimal datatype;
	private BigDecimal uimid;
	private String diyimpl;
	private String defaultvalue;
	private String supportvalue;
	private String relationcolname;
	private List<ViewColumnParamModel> viewColumnParamList;

	protected ViewColumnModel() {}

	public ViewColumnModel(BigDecimal viewid, BigDecimal idx)
	{
		this.viewid = viewid;
		this.idx = idx;
	}

	public BigDecimal getViewid()
	{
		return viewid;
	}

	protected void setViewid(BigDecimal viewid)
	{
		this.viewid = viewid;
	}

	public BigDecimal getIdx()
	{
		return idx;
	}

	protected void setIdx(BigDecimal idx)
	{
		this.idx = idx;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getColname()
	{
		return colname;
	}

	public void setColname(String colname)
	{
		this.colname = colname;
	}

	public String getSqlexp()
	{
		return sqlexp;
	}

	public void setSqlexp(String sqlexp)
	{
		this.sqlexp = sqlexp;
	}

	public BigDecimal getDatatype()
	{
		return datatype;
	}

	public void setDatatype(BigDecimal datatype)
	{
		this.datatype = datatype;
	}

	public BigDecimal getUimid()
	{
		return uimid;
	}

	public void setUimid(BigDecimal uimid)
	{
		this.uimid = uimid;
	}

	public String getDiyimpl()
	{
		return diyimpl;
	}

	public void setDiyimpl(String diyimpl)
	{
		this.diyimpl = diyimpl;
	}

	public String getDefaultvalue()
	{
		return defaultvalue;
	}

	public void setDefaultvalue(String defaultvalue)
	{
		this.defaultvalue = defaultvalue;
	}

	public String getSupportvalue()
	{
		return supportvalue;
	}

	public void setSupportvalue(String supportvalue)
	{
		this.supportvalue = supportvalue;
	}

	public String getRelationcolname()
	{
		return relationcolname;
	}

	public void setRelationcolname(String relationcolname)
	{
		this.relationcolname = relationcolname;
	}

	public List<ViewColumnParamModel> getViewColumnParamList()
	{
		return viewColumnParamList;
	}

	public void setViewColumnParamList(List<ViewColumnParamModel> viewColumnParamList)
	{
		this.viewColumnParamList = viewColumnParamList;
	}

	public void addViewColumnParam(ViewColumnParamModel viewColumnParam)
	{
		if(viewColumnParamList==null) viewColumnParamList = new ArrayList<ViewColumnParamModel>();
		viewColumnParamList.add(viewColumnParam);
	}

	@Override
	public String getRefTableName()
	{
		return "xlv2_viewcolumn";
	}
}