package xlsys.base.model;

import java.math.BigDecimal;
import java.util.List;
import java.util.ArrayList;

/**
 * This class is automatically generated by the program of Lewis.
 * @author Lewis
 *
 */
public class ViewQueryParamModel implements ITableModel
{
	private static final long serialVersionUID = -6696658059286975473L;
	
	private BigDecimal viewid;
	private BigDecimal idx;
	private String name;
	private String colname;
	private BigDecimal datatype;
	private BigDecimal uimid;
	private String diyimpl;
	private String defaultvalue;
	private String supportvalue;
	private List<ViewQueryParamParamModel> viewQueryParamParamList;

	protected ViewQueryParamModel() {}

	public ViewQueryParamModel(BigDecimal viewid, BigDecimal idx)
	{
		this.viewid = viewid;
		this.idx = idx;
	}

	public BigDecimal getViewid()
	{
		return viewid;
	}

	protected void setViewid(BigDecimal viewid)
	{
		this.viewid = viewid;
	}

	public BigDecimal getIdx()
	{
		return idx;
	}

	protected void setIdx(BigDecimal idx)
	{
		this.idx = idx;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getColname()
	{
		return colname;
	}

	public void setColname(String colname)
	{
		this.colname = colname;
	}

	public BigDecimal getDatatype()
	{
		return datatype;
	}

	public void setDatatype(BigDecimal datatype)
	{
		this.datatype = datatype;
	}

	public BigDecimal getUimid()
	{
		return uimid;
	}

	public void setUimid(BigDecimal uimid)
	{
		this.uimid = uimid;
	}

	public String getDiyimpl()
	{
		return diyimpl;
	}

	public void setDiyimpl(String diyimpl)
	{
		this.diyimpl = diyimpl;
	}

	public String getDefaultvalue()
	{
		return defaultvalue;
	}

	public void setDefaultvalue(String defaultvalue)
	{
		this.defaultvalue = defaultvalue;
	}

	public String getSupportvalue()
	{
		return supportvalue;
	}

	public void setSupportvalue(String supportvalue)
	{
		this.supportvalue = supportvalue;
	}

	public List<ViewQueryParamParamModel> getViewQueryParamParamList()
	{
		return viewQueryParamParamList;
	}

	public void setViewQueryParamParamList(List<ViewQueryParamParamModel> viewQueryParamParamList)
	{
		this.viewQueryParamParamList = viewQueryParamParamList;
	}

	public void addViewQueryParamParam(ViewQueryParamParamModel viewQueryParamParam)
	{
		if(viewQueryParamParamList==null) viewQueryParamParamList = new ArrayList<ViewQueryParamParamModel>();
		viewQueryParamParamList.add(viewQueryParamParam);
	}

	@Override
	public String getRefTableName()
	{
		return "xlv2_viewqueryparam";
	}
}