package xlsys.base.model;

import java.math.BigDecimal;

/**
 * This class is automatically generated by the program of Lewis.
 * @author Lewis
 *
 */
public class ViewParamModel implements ITableModel
{
	private static final long serialVersionUID = 6210362938349458857L;
	
	private BigDecimal viewid;
	private String attrname;
	private String attrvalue;

	protected ViewParamModel() {}

	public ViewParamModel(BigDecimal viewid, String attrname)
	{
		this.viewid = viewid;
		this.attrname = attrname;
	}

	public BigDecimal getViewid()
	{
		return viewid;
	}

	protected void setViewid(BigDecimal viewid)
	{
		this.viewid = viewid;
	}

	public String getAttrname()
	{
		return attrname;
	}

	protected void setAttrname(String attrname)
	{
		this.attrname = attrname;
	}

	public String getAttrvalue()
	{
		return attrvalue;
	}

	public void setAttrvalue(String attrvalue)
	{
		this.attrvalue = attrvalue;
	}

	@Override
	public String getRefTableName()
	{
		return "xlv2_viewparam";
	}
}